apiVersion: apps/v1
kind: Deployment
metadata:
  name: ton-chain-deployment
  labels:
    app: ton-chain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ton-chain
  template:
    metadata:
      labels:
        app: ton-chain
    spec:
      containers:
        - name: ton-chain
          image: image:v2
          env:
            - name: PORT
              value: "3000"
            - name: TON_HISTORICAL
              value: https://scalable-api.tonwhales.com/jsonRPC
            - name: TON_ENDPOINTS
              value: https://node-1.servers.tonwhales.com/jsonRPC,https://node-2.servers.tonwhales.com/jsonRPC
            - name: STORAGE
              valueFrom:
                secretKeyRef:
                  name: atlas-cluster
                  key: connection
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
